---
iTrust_repo: https://github.ncsu.edu/smirhos/iTrust-v23.git
home_path: /root
iTrust_local_path: /root/iTrust
iTrust_war_path: "{{iTrust_local_path}}/iTrust/target/iTrust-23.0.0.war"
db_server_url: "192.168.33.101"
